apiVersion: apps/v1
kind: Deployment
metadata:
  name: drivethru-deployment
  namespace: "default"
  labels:
    {{ template "helm.labels" . }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: drivethru
  template:
    metadata:
      labels:
        app: drivethru
    spec:
      containers:
        - name: drivethru-python
          imagePullPolicy: IfNotPresent
          image: drivethru:20221226
          env:
            - name: SECRET_KEY
              value: "change me"
            - name: DATABASE_URL
              value: "postgres://drivethru:drivethru@postgres-service/drivethru"
            - name: PORT
              value: "8989"
          command: ["python", "manage.py", "runserver", "0.0.0.0:8989"]
          ports:
            - containerPort: 8989
          livenessProbe:
            httpGet:
              port: 8989
              path: /status
            initialDelaySeconds: 5
            periodSeconds: 3
